#ifndef _CPU_H_
#define _CPU_H_

/* CPU Implementers */
enum cpu_implementers {
	CPU_VENDOR_ARM = 0x41,
	CPU_VENDOR_BROADCOM,
	CPU_VENDOR_CAVIUM,
	CPU_VENDOR_DEC,
	CPU_VENDOR_INFINEON,
	CPU_VENDOR_MOTOROLA,
	CPU_VENDOR_NVIDIA,
	CPU_VENDOR_APCC,
	CPU_VENDOR_QUALCOMM,
	CPU_VENDOR_MARVELL,
	CPU_VENDOR_INTEL
};

#endif	/* !_CPU_CPU_H_ */
